### ISSUE TITLE
How to get the ELMo vector

### ISSUE THREAD

**Issue by loriqing** [gao-g/metaphor-in-context#1]
Hello, our project team is paying attention to your work. How can I get the ELMo vector?

**Comment by 978749951** [comment]
Hi @gao-g ,
      I also wonder how could I get the ELMO vector?

**Comment by OmniaZayed** [comment]
@gao-g, I think it is becoming important to include the code that you used to obtain the embeddings for ELMo stored in the hdf5 files ;) After studying your code, I think you used the tokenized text strings option to build your vectors, right?

**Comment by SmallBall8** [comment]
您好，亲吻在哪里找第一作者的邮箱呢？

**Comment by gao-g** [comment]
Please check out the README: a link to download elmo vectors is included.
